### ISSUE TITLE
App crashes when credentials are supplied

### ISSUE THREAD

**Issue by hax0rgb** [oversecured/ovaa#2]
After recent changes, the application is not able to authenticate and crashes when creds are supplied.

Verified this on several android devices. Same behaviour.

Following is the logcat output:

```
OpenGLRenderer  W  Failed to set EGL_SWAP_BEHAVIOR on surface 0xeb3f3780, error=EGL_SUCCESS
                   ovaa  D  Processing ovaa@ovaa.com:ovaa
         AndroidRuntime  D  Shutting down VM
                         E  FATAL EXCEPTION: main
                         E  Process: oversecured.ovaa, PID: 5853
                         E  java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getString(int)' on a null object reference
                         E      at oversecured.ovaa.utils.LoginUtils.getLoginUrl(LoginUtils.java:55)
                         E      at oversecured.ovaa.activities.LoginActivity.processLogin(LoginActivity.java:63)
                         E      at oversecured.ovaa.activities.LoginActivity.access$000(LoginActivity.java:22)
                         E      at oversecured.ovaa.activities.LoginActivity$1.onClick(LoginActivity.java:53)
                         E      at android.view.View.performClick(View.java:5198)
                         E      at android.view.View$PerformClick.run(View.java:21147)
                         E      at android.os.Handler.handleCallback(Handler.java:739)
                         E      at android.os.Handler.dispatchMessage(Handler.java:95)
                         E      at android.os.Looper.loop(Looper.java:148)
                         E      at android.app.ActivityThread.main(ActivityThread.java:5417)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                Process  I  Sending signal. PID: 5853 SIG: 9

                            Process oversecured.ovaa (PID: 5853) ended
```

**Comment by bagipro** [comment]
@0xgb 
Thanks, fixed
